FROM apache/airflow:2.9.1-python3.10

COPY requirements.txt /opt/airflow/requirements.txt
RUN pip install -r /requirements.txt

COPY ./dags /opt/airflow/dags
COPY ./data /opt/airflow/data
COPY ./logs /opt/airflow/logs
COPY ./plugins /opt/airflow/plugins
COPY ./upcoming /opt/airflow/upcoming
COPY ./run_spider.py /opt/airflow/run_spider.py

CMD ["airflow scheduler"]