version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.9.1-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR : LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN : postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY : 'fernet_key_dev_123'
      AIRFLOW__CORE__LOAD_EXAMPLES : 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./upcoming:/opt/airflow/upcoming
      - ./requirements.txt:/requirements.txt
      - ./run_spider.py:/opt/airflow/run_spider.py
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: >
      bash -c "pip install -r /requirements.txt && airflow webserver"

  scheduler:
    image: apache/airflow:2.9.1-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR : LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN : postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY : 'fernet_key_dev_123'
      AIRFLOW__CORE__LOAD_EXAMPLES : 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logsd
      - ./plugins:/opt/airflow/plugins
      - ./upcoming:/opt/airflow/upcoming
      - ./requirements.txt:/requirements.txt
      - ./run_spider.py:/opt/airflow/run_spider.py
    depends_on:
      - webserver
    command: >
      bash -c "pip install -r /requirements.txt && airflow scheduler"

  airflow-init:
    image: apache/airflow:2.9.1-python3.10
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR : LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN : postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY : 'fernet_key_dev_123'
      AIRFLOW__CORE__LOAD_EXAMPLES : 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./upcoming:/opt/airflow/upcoming
      - ./requirements.txt:/requirements.txt
      - ./run_spider.py:/opt/airflow/run_spider.py
    entrypoint: >
      bash -c "
        pip install -r /requirements.txt &&
        airflow db migrate &&
        airflow users create --username airflow --password airflow \
          --firstname admin --lastname user --role Admin \
          --email admin@example.com
      "

volumes:
  postgres-db-volume: