#!/bin/bash
set -e


mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`$AIRFLOW_DB\`;
CREATE DATABASE IF NOT EXISTS \`$DJANGO_DB\`;
CREATE DATABASE IF NOT EXISTS \`$API_DB\`;

CREATE USER IF NOT EXISTS '$AIRFLOW_USER'@'%' IDENTIFIED BY '$AIRFLOW_PASSWORD';
CREATE USER IF NOT EXISTS '$DJANGO_USER'@'%' IDENTIFIED BY '$DJANGO_PASSWORD';
CREATE USER IF NOT EXISTS '$API_USER'@'%' IDENTIFIED BY '$API_PASSWORD';

GRANT ALL PRIVILEGES ON \`$AIRFLOW_DB\`.* TO '$AIRFLOW_USER'@'%';
GRANT ALL PRIVILEGES ON \`$DJANGO_DB\`.* TO '$DJANGO_USER'@'%';
GRANT ALL PRIVILEGES ON \`$API_DB\`.* TO '$API_USER'@'%';

FLUSH PRIVILEGES;
EOSQL
